# -*- coding: utf-8 -*-
"""Movies Recommendation System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hX-H40sEGUrNwfPb24pXQhKg5ordVrx1

# **Movies Recommendation System**
"""

import pandas as pd

movies = pd.read_csv('/content/movie_dataset.csv')

movies.head(5)

movies.describe()

movies.info()

movies.isnull().sum()

movies.columns

movies = movies[['id', 'title', 'overview', 'genres']]

movies

movies['tags'] = movies['overview'] + movies['genres']

movies

new_data = movies.drop(columns=['overview', 'genres'])

new_data

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=10000, stop_words='english')

cv

vectors = cv.fit_transform(new_data['tags'].values.astype('U')).toarray()

vectors.shape

from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

similarity

new_data[new_data['title']=="The Godfather"].index[0]

distance = sorted(list(enumerate(similarity[1])), reverse=True, key=lambda vectors:vectors[1])
for i in distance[0:5]:
  print(new_data.iloc[i[0]].title)

def recommend(movies):
  index = new_data[new_data['title']==movies].index[0]
  distance = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda vectors:vectors[1])
  for i in distance[0:5]:
    print(new_data.iloc[i[0]].title)

recommend('Iron Man')

import pickle

pickle.dump(new_data, open('movies.pkl', 'wb'))

pickle.dump(similarity, open('similarity.pkl', 'wb'))

pickle.load(open('movies.pkl', 'rb'))